---
title: "Analyse cvc tracks"
output: html_notebook
---

!! Run analyse_tracks.Rmd first to load the tracks.

```{r}
# clean up CVC signal

library(EBImage)
morph_kern <- makeBrush(5, shape='box')
df_links_spots_adj <- df_links_spots
df_links_spots_adj$TRACK_CVC_REGIONS <- 0
df_links_spots_adj$TRACK_NO_SEG_REGIONS <- 0

# go through all tracks and clean up CVC signal
for (cur_norm_id in unique(df_links_spots_adj$NORM_ID)) {
  cur_cvc <- df_links_spots_adj[(df_links_spots_adj$NORM_ID == cur_norm_id),]$IS_CVC_POS
  cur_seg <- df_links_spots_adj[(df_links_spots_adj$NORM_ID == cur_norm_id),]$HAS_NO_SEG
  
  dat_to_clean <- list(
    list(c(cur_cvc), "IS_CVC_POS", "TRACK_CVC_REGIONS"),
    list(c(cur_seg), "HAS_NO_SEG", "TRACK_NO_SEG_REGIONS")
  )
  
  # close gaps between signal and remove isolated signals
  for (cur_clean in dat_to_clean){
    # prepare data
    cur_dat <- array(as.numeric(unlist(cur_clean[[1]])), dim=c(1, length(cur_clean[[1]])))
    
    if (ncol(cur_dat) > 0){
      cur_closed <- closing(cur_dat, morph_kern)
      cur_opened <- opening(cur_closed, morph_kern)
      
      cur_morph <- cur_opened[1,]
      df_links_spots_adj[(df_links_spots_adj$NORM_ID == cur_norm_id),][[cur_clean[[2]]]] <- cur_morph
      
      cur_counter <- 0
      last_val <- -1
      
      for (i in cur_morph){
        if (i != last_val && i == 1){
          cur_counter <- cur_counter + 1
        }
        
        last_val <- i
      }
      
      df_links_spots_adj[(df_links_spots_adj$NORM_ID == cur_norm_id),][[cur_clean[[3]]]] <- cur_counter
    }
  }
}
```

```{r fig_track_cvc, fig.height = 1, fig.width = 1.3}
# Show track with CVC signal
library(ggplot2)

show_cvc_track <- function(well, site, track_id){
  # define example
  cur_norm_id <- paste("w", well, "_s", site, "_i", track_id, sep = "")
  
  cur_dat_to_plot <- df_links_spots_adj[df_links_tracks$NORM_ID == cur_norm_id,]
  
  # order by frame
  cur_dat_to_plot <- cur_dat_to_plot[with(cur_dat_to_plot, order(FRAME)),]
  
  # define timing
  timepoints <- 160
  ylim_max <- 6

  ggplot(data = cur_dat_to_plot, aes(x = FRAME/10)) +
    geom_area(aes(y = NO_DC_SEG * ylim_max), fill = alpha("Gray", 0.7)) +
    geom_area(aes(y = IS_CVC_POS * ylim_max), fill = alpha("Magenta", 0.7)) +
    geom_line(aes(y = VELOCITY), colour = "Black") +
    theme_classic() +
    ylim(0, ylim_max) +
    xlim(0, timepoints/10) +
    # geom_hline(yintercept = 5, linetype = "dashed", colour = "grey") +
    xlab("Time (h)") +
    ylab("Velocity (μm/min)") +
    theme(strip.text.y = element_text(size = 6))
}

show_cvc_track(7, 0, 229)
show_cvc_track(7, 0, 8)
show_cvc_track(6, 2, 514)
```



```{r fig_tracks, fig.height = 1, fig.width = 1.5}
# Show CP measures for track
# !! run analyse_morphology.Rmd first to load df_dc

library(ggplot2)

show_ecc_track <- function(well, site, track_id, manual_overlap){
  # define example
  cur_norm_id <- paste("w", well, "_s", site, "_i", track_id, sep = "")
  
  cur_dat_to_plot <- df_links_spots_cp[df_links_spots_cp$NORM_ID == cur_norm_id,]
  
  # order by frame
  cur_dat_to_plot <- cur_dat_to_plot[with(cur_dat_to_plot, order(FRAME)),]
  
  # define timing
  timepoints <- 160
  ylim_max <- 1

  ggplot(data = cur_dat_to_plot, aes(x = FRAME/10)) +
    geom_area(aes(y = ON_DONOR * ylim_max), fill = alpha("#cccc00", 0.7)) +
    geom_hline(yintercept = 0.6, linetype = "solid", colour = "grey", size = 1.5) +
    geom_line(aes(y = AreaShape_FormFactor), colour = "Black") +
    theme_classic() +
    ylim(0, ylim_max) +
    xlim(0, timepoints/10) +
    # geom_hline(yintercept = 5, linetype = "dashed", colour = "grey") +
    xlab("Time (h)") +
    ylab("FormFactor\n(1: circle; 0: irregular)") +
    theme(strip.text.y = element_text(size = 6))
}

cp_info <- c("AreaShape_Eccentricity", "AreaShape_FormFactor", "AreaShape_Compactness",
             "Metadata_Well", "Metadata_Site", "Metadata_Time", "ObjectNumber_in_Image")
cur_cp_df <- df_dc[df_dc$exp == "N4-2-13" &
                     df_dc$sample == "COLI",
                   cp_info]
df_links_spots_adj$time <- df_links_spots_adj$FRAME

# link CP information to tracks
df_links_spots_cp <- merge(
  x = df_links_spots_adj,
  y = cur_cp_df,
  by.x = c("well", "site", "time", "CP_SEG_ID"),
  by.y = c("Metadata_Well", "Metadata_Site", "Metadata_Time", "ObjectNumber_in_Image"),
  all.x = TRUE
)

show_ecc_track(7, 0, 8)
show_ecc_track(6, 2, 514)

cur_dat_to_plot <- df_links_spots_cp[df_links_spots_cp$NORM_ID == "w7_s0_i8",]
```

```{r}
# normalise frames
df_links_spots_adj$NORM_FRAME <- -1

# normalise frames
cur_time_aggr <- aggregate(FRAME ~ NORM_ID, df_links_spots_adj, min)

for (cur_id in cur_time_aggr$NORM_ID){
  df_links_spots_adj[df_links_spots_adj$NORM_ID == cur_id,]$NORM_FRAME <-
    df_links_spots_adj[df_links_spots_adj$NORM_ID == cur_id,]$FRAME - cur_time_aggr[cur_time_aggr$NORM_ID == cur_id,]$FRAME
}
```

Show different classes of tracks
```{r fig_track_classes, fig.height = 1.5, fig.width = 1.5}
library(dplyr)
library(reshape2)
library(ggplot2)

plot_track_class <- function(track_class, class_levels, ylim_max){
  dat_freq <- table(cur_dat_to_plot[,c('donor', track_class)])
  
  # melt dataframe
  cur_df_melt <- melt(dat_freq, id.vars = "donor")
  cur_df_melt$donor <- factor(cur_df_melt$donor, levels = donor_levels)
  cur_df_melt[, track_class] <- factor(cur_df_melt[, track_class], levels = class_levels)
  
  ggplot(cur_df_melt, aes(x = donor, y = value, fill=cur_df_melt[,track_class])) +
    geom_bar(stat='identity') +
    theme_classic() +
    xlab("Donor") +
    ylab("Count") +
    ylim(0, ylim_max) +
    scale_fill_manual(
      name="Donor",
      values=c("Black", "Magenta"))+
    guides(color = guide_legend(nrow=1)) +
      theme(
        legend.justification = c(0.98,0.98),
        legend.position = c(0.98,0.98),
        legend.text = element_text(size = 10),
        legend.key.width = unit(0.5,"line"),
        legend.key.height = unit(0.5,"line"),
        legend.title = element_blank(),
        #legend.position="none",
        legend.box.background = element_rect(colour = "black"),
        legend.margin = margin(c(3,3,3,3)),
        strip.text.x = element_blank()
        ) 
}

dat_to_plot <- df_links_spots_adj

# CVC classes
cur_aggr <- aggregate(IS_CVC_POS ~ NORM_ID, dat_to_plot, sum)
cvc_norm_ids <- cur_aggr[cur_aggr$IS_CVC_POS >= 20,]$NORM_ID
dat_to_plot$TRACK_CLASS_CVC <- 0
dat_to_plot[dat_to_plot$TRACK_CVC_REGIONS >= 1 &
              dat_to_plot$NORM_ID %in% cvc_norm_ids, ]$TRACK_CLASS_CVC <- 1

# Acquisition classes
dat_to_plot$TRACK_CLASS_ACQ <- 0
preloaded_norm_ids <- unique(dat_to_plot[
  dat_to_plot$TRACK_CLASS_CVC == 1 &
    dat_to_plot$NORM_FRAME < 5 &
    dat_to_plot$IS_CVC_POS == 1, ]$NORM_ID)
dat_to_plot[!(dat_to_plot$NORM_ID %in% preloaded_norm_ids),]$TRACK_CLASS_ACQ <- 1

dat_to_plot <- merge(
  x = df_links_spots_adj,
  y = dat_to_plot[, c("NORM_ID", "NORM_FRAME", "TRACK_CLASS_CVC", "TRACK_CLASS_ACQ")],
  by = c("NORM_ID", "NORM_FRAME"),
  all.x = TRUE
)

cur_dat_to_plot <- dat_to_plot %>% 
  dplyr::group_by(NORM_ID, donor, ERROR_CODE) %>% 
  dplyr::summarise(max_NORM_FRAME = max(NORM_FRAME, na.rm = TRUE),
            sum_NO_DC_SEG = sum(NO_DC_SEG, na.rm = TRUE)) %>%
  dplyr::ungroup()

# account for NORM_FRAME starting at '0'
cur_dat_to_plot$max_NORM_FRAME <- cur_dat_to_plot$max_NORM_FRAME + 1

# take ratio of unsegmented ratio
cur_dat_to_plot$SEG_RATIO <- (1 - (cur_dat_to_plot$sum_NO_DC_SEG / cur_dat_to_plot$max_NORM_FRAME))
cur_dat_to_plot$TRACK_CLASS_SEG <- 0
cur_dat_to_plot[cur_dat_to_plot$SEG_RATIO >= 0.9,]$TRACK_CLASS_SEG <- 1

# merge CLASS_SEG back to dataframe
dat_to_plot <- merge(
  x = dat_to_plot,
  y = cur_dat_to_plot[, c("NORM_ID", "TRACK_CLASS_SEG", "max_NORM_FRAME")],
  by = c("NORM_ID"),
  all.x = TRUE
)

cur_dat_to_plot <- cur_dat_to_plot
class_seg_levels <- c("< 90% Segmentation", "≥ 90% Segmentation")
cur_dat_to_plot[cur_dat_to_plot$TRACK_CLASS_SEG == 0,]$TRACK_CLASS_SEG <- class_seg_levels[1]
cur_dat_to_plot[cur_dat_to_plot$TRACK_CLASS_SEG == 1,]$TRACK_CLASS_SEG <- class_seg_levels[2]
cur_dat_to_plot$TRACK_CLASS_SEG <- factor(cur_dat_to_plot$TRACK_CLASS_SEG, levels = class_seg_levels)
plot_track_class('TRACK_CLASS_SEG', class_seg_levels, 400)

# How many many have no signal in the first 30 min?
cur_dat_to_plot <- dat_to_plot[dat_to_plot$TRACK_CLASS_SEG == 1,]
class_acq_levels <- c("CVC+ in first 30 min", "CVC- in first 30 min")
cur_dat_to_plot[cur_dat_to_plot$TRACK_CLASS_ACQ == 0,]$TRACK_CLASS_ACQ <- class_acq_levels[1]
cur_dat_to_plot[cur_dat_to_plot$TRACK_CLASS_ACQ == 1,]$TRACK_CLASS_ACQ <- class_acq_levels[2]
cur_dat_to_plot$TRACK_CLASS_ACQ <- factor(cur_dat_to_plot$TRACK_CLASS_ACQ,
                                           levels = class_acq_levels)
cur_dat_to_plot <- cur_dat_to_plot[cur_dat_to_plot$NORM_FRAME == 0,]
dat_freq <- table(cur_dat_to_plot[,c('donor', 'TRACK_CLASS_ACQ')])
plot_track_class('TRACK_CLASS_ACQ', class_acq_levels, 400)

# How many CVC+ tracks are among the acceptable segmented tracks?
cur_dat_to_plot <- dat_to_plot[dat_to_plot$TRACK_CLASS_SEG == 1 &
                                 dat_to_plot$TRACK_CLASS_ACQ == 1,]
class_cvc_levels <- c("< 2 h CVC+", "≥ 2 h CVC+")
cur_dat_to_plot[cur_dat_to_plot$TRACK_CLASS_CVC == 0,]$TRACK_CLASS_CVC <- class_cvc_levels[1]
cur_dat_to_plot[cur_dat_to_plot$TRACK_CLASS_CVC == 1,]$TRACK_CLASS_CVC <- class_cvc_levels[2]
cur_dat_to_plot$TRACK_CLASS_CVC <- factor(cur_dat_to_plot$TRACK_CLASS_CVC,
                                           levels = class_cvc_levels)
cur_dat_to_plot <- cur_dat_to_plot[cur_dat_to_plot$NORM_FRAME == 0,]
plot_track_class('TRACK_CLASS_CVC', class_cvc_levels, 400)
```

```{r}
# get examples of acquiring DCs ordered by duration of track
cur_dat_to_plot <- dat_to_plot[
  dat_to_plot$TRACK_CLASS_SEG == 1 &
  dat_to_plot$TRACK_CLASS_CVC == 1 &
  dat_to_plot$TRACK_CLASS_ACQ == 1,
  # dat_to_plot$ERROR_CODE == 0,
]

# order by frame
cur_dat_to_plot <- cur_dat_to_plot[with(cur_dat_to_plot, order(-max_NORM_FRAME, FRAME)),]

# select ids which are ok and the ones with errors
norm_ids_ok <- c("w7_s0_i8", "w6_s2_i514")
cur_dat_to_plot_ok <- cur_dat_to_plot[cur_dat_to_plot$NORM_ID %in% norm_ids_ok,]
cur_dat_to_plot_errors <- cur_dat_to_plot[!(cur_dat_to_plot$NORM_ID %in% norm_ids_ok),]

# define timing
timepoints <- 160
ylim_max <- 6
```

```{r fig_cvc_tracks_errors, fig.height = 1, fig.width = 4}
ggplot(data = cur_dat_to_plot_errors, aes(x = FRAME/10)) +
  geom_area(aes(y = NO_DC_SEG * ylim_max), fill = alpha("Gray", 0.7)) +
  geom_area(aes(y = IS_CVC_POS * ylim_max), fill = alpha("Magenta", 0.7)) +
  geom_line(aes(y = VELOCITY), colour = "Black") +
  theme_classic() +
  ylim(0, ylim_max) +
  xlim(0, timepoints/10) +
  # geom_hline(yintercept = 5, linetype = "dashed", colour = "grey") +
  xlab("Time (h)") +
  ylab("Velocity (μm/min)") +
  #theme(strip.text.y = element_text(size = 6)) +
  theme(strip.text.x = element_blank()) +
  facet_wrap(~NORM_ID, nrow = 1)
```

```{r fig_cvc_tracks_ok, fig.height = 1, fig.width = 1.5}
ggplot(data = cur_dat_to_plot_ok[cur_dat_to_plot_ok$NORM_ID == norm_ids_ok[1],], aes(x = FRAME/10)) +
  geom_area(aes(y = NO_DC_SEG * ylim_max), fill = alpha("Gray", 0.7)) +
  geom_area(aes(y = IS_CVC_POS * ylim_max), fill = alpha("Magenta", 0.7)) +
  geom_line(aes(y = VELOCITY), colour = "Black") +
  theme_classic() +
  ylim(0, ylim_max) +
  xlim(0, timepoints/10) +
  # geom_hline(yintercept = 5, linetype = "dashed", colour = "grey") +
  xlab("Time (h)") +
  ylab("Velocity (μm/min)") +
  #theme(strip.text.y = element_text(size = 6)) +
  theme(strip.text.x = element_blank()) +
  facet_wrap(~NORM_ID, ncol = 1)

ggplot(data = cur_dat_to_plot_ok[cur_dat_to_plot_ok$NORM_ID == norm_ids_ok[2],], aes(x = FRAME/10)) +
  geom_area(aes(y = NO_DC_SEG * ylim_max), fill = alpha("Gray", 0.7)) +
  geom_area(aes(y = IS_CVC_POS * ylim_max), fill = alpha("Magenta", 0.7)) +
  geom_line(aes(y = VELOCITY), colour = "Black") +
  theme_classic() +
  ylim(0, ylim_max) +
  xlim(0, timepoints/10) +
  # geom_hline(yintercept = 5, linetype = "dashed", colour = "grey") +
  xlab("Time (h)") +
  ylab("Velocity (μm/min)") +
  #theme(strip.text.y = element_text(size = 6)) +
  theme(strip.text.x = element_blank()) +
  facet_wrap(~NORM_ID, ncol = 1)
```