---
title: "Analyse TRACKMATE tracks"
output: html_notebook
---

Analyse tracks from TRACKMATE results for speed. Try to find measures to identify tracks that might need correction + looking at the mean speed to see if there is a difference between the different donor types.

```{r}
library(hash)

# read in file
df_stats_base_dir <- "/Users/dominiks/Desktop/ANALYSIS/N4/"
experiments <- c("N4-2-13")
wells <- seq(5, 8)
sites <- seq(0, 2)
analysis_dir <- "/ANALYSIS/TRACKING_DC/"
clips_dir <- "/ANALYSIS/TRACKING_DC_INDV/"
examples_dir <- "/ANALYSIS/TRACKING_DC_EXAMPLES/"
stats_file <- "-tracks.csv"
corrections_file <- "corrections.csv"
donor_levels <- c("PF", "3T3", "B16", "NONE")

# well mapping
well_donor_map <- hash(c(
  "N4-2-13" = hash(c(
    "5" = "B16", "6" = "3T3", "7" = "PF", "8" = "NONE"
  ))
))

dfs_pool <- list()
for (cur_exp in experiments) {
  for (cur_well in wells) {
    for (cur_site in sites) {
      cur_df <- read.csv(
        paste(df_stats_base_dir, cur_exp, analysis_dir,
              "w", cur_well, "_s", cur_site,
              stats_file, sep = ""))
      
      cur_df$exp <- cur_exp
      cur_df$well <- cur_well
      cur_df$site <- cur_site
      cur_df$donor <- "NONE"
      
      # map donors to wells
      cur_df$donor <- well_donor_map[[cur_exp]][[1]][[as.character(cur_well)]]
      
      dfs_pool[[paste(cur_exp, "_w", cur_well, "_s", cur_site, sep = "")]] <- cur_df
      remove(cur_df)
    }
  }
}

# merge experiments
df_tracking <- do.call("rbind", dfs_pool)
```

```{r}
# load corrections and remove tracks that would need corrections
dfs_pool <- list()
for (cur_exp in experiments) {
  cur_df <- read.csv(
    paste(df_stats_base_dir, cur_exp, analysis_dir,
          corrections_file, sep = ""))
  
  cur_df$exp <- cur_exp
  cur_df$donor <- "NONE"
  
  # map donors to wells
  df_wells <- unique(cur_df$well)
  df_wells <- df_wells[!is.na(df_wells)]
  
  for (cur_well in df_wells){
    cur_df[cur_df$well == cur_well,]$donor <- well_donor_map[[cur_exp]][[1]][[as.character(cur_well)]]
  }
  
  dfs_pool[[paste(cur_exp, sep = "")]] <- cur_df
  remove(cur_df)
}

# merge experiments
df_corrections <- do.call("rbind", dfs_pool)

# merge corrections to tracks
df_tracking_with_corrections <- merge(
  df_tracking,
  df_corrections,
  by = c("exp", "well", "site", "donor", "TRACK_ID"),
  all.x = T)

df_tracking_with_corrections$ERROR_CODE <- as.character(df_tracking_with_corrections$ERROR_CODE)
df_tracking_with_corrections$COMMENT <- as.character(df_tracking_with_corrections$COMMENT)

df_tracking_with_corrections[is.na(df_tracking_with_corrections$ERROR_CODE),]$ERROR_CODE <- 0
df_tracking_with_corrections[is.na(df_tracking_with_corrections$COMMENT),]$COMMENT <- ""
```

Plot tracking errors
```{r fig_track_errors, fig.height = 1.5, fig.width = 1.5}
library(reshape2)
library(ggplot2)

# categorise tracks into accepted, correctable and removed
df_tracking_with_corrections$OUTCOME <- "NA"
df_tracking_with_corrections[df_tracking_with_corrections$ERROR_CODE == 0,]$OUTCOME <- "Accepted"
df_tracking_with_corrections[df_tracking_with_corrections$ERROR_CODE %in% c(1,2),]$OUTCOME <- "Correctable"
df_tracking_with_corrections[df_tracking_with_corrections$ERROR_CODE %in% c(3,4,5),]$OUTCOME <- "Removed"

dat_to_plot <- df_tracking_with_corrections[, c("donor", "OUTCOME")]
dat_freq <- table(dat_to_plot)

# melt dataframe
cur_df_melt <- melt(dat_freq, id.vars = "donor")
cur_df_melt$donor <- factor(cur_df_melt$donor, levels = donor_levels)

ggplot(cur_df_melt, aes(x = donor, y = value, fill=OUTCOME)) +
    geom_bar(stat='identity') +
    theme_classic() +
    xlab("Donor") +
    ylab("Count") +
    scale_fill_manual(
      name="Donor",
      values=c("Black", "Cyan", "Magenta"))+
  guides(color = guide_legend(nrow=1)) +
    theme(
      legend.justification = c(0.98,0.98),
      legend.position = c(0.98,0.98),
      legend.text = element_text(size = 10),
      legend.key.width = unit(0.5,"line"),
      legend.key.height = unit(0.5,"line"),
      legend.title = element_blank(),
      #legend.position="none",
      legend.box.background = element_rect(colour = "black"),
      legend.margin = margin(c(3,3,3,3)),
      strip.text.x = element_blank()
      ) 
```

Connect spots with CVC signal from FIJI (extract_sampling_dc.ijm) and Python (link_cvc_to_dc_tracks.py).
```{r}
library(tidyr)
library("RColorBrewer")

# load spot and links data
spots_file <- "-spots_cvc.csv"
links_file <- "-links.csv"

wells_with_donors <- seq(5, 7)

dfs_spots_pool <- list()
dfs_links_pool <- list()
for (cur_exp in experiments) {
  for (cur_well in wells_with_donors) {
    for (cur_site in sites) {
      cur_spots_df <- read.csv(
        paste(df_stats_base_dir, cur_exp, analysis_dir,
              "w", cur_well, "_s", cur_site,
              spots_file, sep = ""))
      
      cur_links_df <- read.csv(
        paste(df_stats_base_dir, cur_exp, analysis_dir,
              "w", cur_well, "_s", cur_site,
              links_file, sep = ""))
      
      cur_spots_df$exp <- cur_exp
      cur_spots_df$well <- cur_well
      cur_spots_df$site <- cur_site
      cur_spots_df$donor <- "NONE"
      
      cur_links_df$exp <- cur_exp
      cur_links_df$well <- cur_well
      cur_links_df$site <- cur_site
      cur_links_df$donor <- "NONE"
      
      # map donors to wells
      cur_spots_df$donor <- well_donor_map[[cur_exp]][[1]][[as.character(cur_well)]]
      cur_links_df$donor <- well_donor_map[[cur_exp]][[1]][[as.character(cur_well)]]
      
      dfs_spots_pool[[paste(cur_exp, "_w", cur_well, "_s", cur_site, sep = "")]] <- cur_spots_df
      dfs_links_pool[[paste(cur_exp, "_w", cur_well, "_s", cur_site, sep = "")]] <- cur_links_df
      
      remove(cur_spots_df)
      remove(cur_links_df)
    }
  }
}

# merge experiments
df_spots <- do.call("rbind", dfs_spots_pool)
df_links <- do.call("rbind", dfs_links_pool)

# normalise IDs
df_spots$NORM_ID <- paste(
  "w", df_spots$well,
  "_s", df_spots$site,
  "_i", df_spots$TRACK_ID,
  sep = "")
df_links$NORM_ID <- paste(
  "w", df_links$well,
  "_s", df_links$site,
  "_i", df_links$TRACK_ID,
  sep = "")
df_tracking$NORM_ID <- paste(
  "w", df_tracking$well,
  "_s", df_tracking$site,
  "_i", df_tracking$TRACK_ID,
  sep = "")
df_tracking_with_corrections$NORM_ID <- paste(
  "w", df_tracking_with_corrections$well,
  "_s", df_tracking_with_corrections$site,
  "_i", df_tracking_with_corrections$TRACK_ID,
  sep = "")

# merge links and track information
df_links_tracks <- merge(
  df_links,
  df_tracking_with_corrections[,c("NORM_ID","ERROR_CODE")],
  by = "NORM_ID",
  all.x = T)

# merge spots to links
df_links_spots <- merge(
  df_links_tracks,
  df_spots[, c("NORM_ID", "ID", "FRAME", "IS_CVC_POS", "NO_DC_SEG", "CP_SEG_ID", "ON_DONOR")],
  by.x = c("NORM_ID", "SPOT_TARGET_ID"),
  by.y = c("NORM_ID", "ID"),
  all.x = T)
```

```{r fig_track_velocity, fig.height = 1, fig.width = 1.5}
# Show velocity of one track and highlight a defined area
library(ggplot2)

show_highlighted_track <- function(well, site, track_id, timespan){
  # define example
  cur_norm_id <- paste("w", well, "_s", site, "_i", track_id, sep = "")
  cur_timespan <- timespan
  
  cur_dat_to_plot <- df_links_spots[df_links_tracks$NORM_ID == cur_norm_id,]
  
  # order by frame
  cur_dat_to_plot <- cur_dat_to_plot[with(cur_dat_to_plot, order(FRAME)),]
  
  # get start time
  cur_start_time <- min(cur_dat_to_plot$FRAME)
  
  # calculuate stop and start region
  cur_span_start <- cur_start_time + ((cur_timespan[1] - 1))
  cur_span_stop <- cur_start_time + ((cur_timespan[2] - 1))
  highlight_span <- seq(cur_span_start,cur_span_stop)
  
  # highlight timespan
  cur_dat_to_plot$TIME_HIGHLIGHT <- 0
  cur_dat_to_plot[cur_dat_to_plot$FRAME %in% highlight_span,
                  ]$TIME_HIGHLIGHT <- 1
  
  # define timing
  timepoints <- 160
  ylim_max <- 6
  
  print(highlight_span)
  
  ggplot(data = cur_dat_to_plot, aes(x = FRAME/10)) +
    geom_area(aes(y = TIME_HIGHLIGHT * ylim_max), fill = "Gray") +
    geom_line(aes(y = VELOCITY), colour = "Black") +
    theme_classic() +
    ylim(0, ylim_max) +
    xlim(0, timepoints/10) +
    # geom_hline(yintercept = 5, linetype = "dashed", colour = "grey") +
    xlab("Time (h)") +
    ylab("Velocity (μm/min)") +
    theme(strip.text.y = element_text(size = 6))
}

show_highlighted_track(6, 0, 23, c(78, 82))
show_highlighted_track(7, 1, 381, c(30, 33))
show_highlighted_track(6, 2, 8, c(27, 33))
show_highlighted_track(5, 2, 408, c(10, 13))
show_highlighted_track(7, 0, 229, c(30, 55))
```

Plot measures from tracks.
```{r fig_track_measures, fig.height = 1.5, fig.width = 1.3}
require(ggplot2)
library(scales)

cur_df_plot <- df_tracking_with_corrections[df_tracking_with_corrections$ERROR_CODE == 0,]

donor_levels <- c("PF", "3T3", "B16", "NONE")
cur_df_plot$donor <- factor(cur_df_plot$donor, levels = donor_levels)

ggplot(data = cur_df_plot, aes(x=factor(donor), y=TRACK_DISPLACEMENT)) +
  geom_jitter(alpha=0.5, width = 0.3, col="Gray") +
  geom_violin(alpha=0) +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text = element_blank()
        ) +
  xlab ("Donors") + ylab("Displacement (μm)") +
  stat_summary(fun.y=mean, geom="point", size=2, shape=18, color="Magenta")
ggplot(data = cur_df_plot, aes(x=factor(donor), y=TRACK_DURATION/60)) +
  geom_jitter(alpha=0.5, width = 0.3, col="Gray") +
  geom_violin(alpha=0) +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text = element_blank()
        ) +
  xlab ("Donors") + ylab("Track duration (h)") +
  stat_summary(fun.y=mean, geom="point", size=2, shape=18, color="Magenta")
ggplot(data = cur_df_plot, aes(x=factor(donor), y=TRACK_MEAN_SPEED)) +
  geom_jitter(alpha=0.5, width = 0.3, col="Gray") +
  geom_violin(alpha=0) +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text = element_blank()
        ) +
  xlab ("Donors") + ylab("Velocity (μm/min)") +
  stat_summary(fun.y=mean, geom="point", size=2, shape=18, color="Magenta")
```