---
title: "Analyse DCs overlapping with donors"
output: html_notebook
---

---
MON 22/10/2018
---

Run FIJI script (extract_overlapping_dc.ijm) and analyse results.
```{r}
library(hash)

# read in file
df_stats_base_dir <- "/Users/dominiks/Desktop/ANALYSIS/N4/"
experiments <- c("N4-2-7", "N4-2-9", "N4-2-13")
analysis_dir <- "/ANALYSIS/OVERLAPPING_DC/"
stats_file <- "stats.csv"

dfs_overlap <- list()
for (cur_exp in experiments) {
  cur_df_overlap <- read.csv(
    paste(df_stats_base_dir, cur_exp, analysis_dir, stats_file, sep = ""))
  
  cur_df_overlap$exp <- cur_exp
  
  dfs_overlap[[cur_exp]] <- cur_df_overlap
  remove(cur_df_overlap)
}

# merge experiments
df_overlap <- do.call("rbind", dfs_overlap)

# calculate ratios
df_overlap$ratio_dc_overlapping <- df_overlap$dc_overlapping_count/df_overlap$dc_count
df_overlap$ratio_donor_area <- df_overlap$donor_dil_area/df_overlap$total_area
df_overlap$ratio_dc_donor <- df_overlap$ratio_dc_overlapping/df_overlap$ratio_donor_area

# --- START SAT 03/11/2018
# convert columns to df_dc standard
names(df_overlap)[names(df_overlap) == 'frame'] <- 'time'

image_donor_map <- hash(c(
  "N4-2-7" = hash(c(
    "Well1_Seq0000" = "B16", "Well3_Seq0002" = "B16",
    "Well2_Seq0001" = "3T3", "Well4_Seq0003" = "3T3",
    "Well5_Seq0007" = "PF", "Well7_Seq0005" = "PF"
  )),
  "N4-2-9" = hash(c(
    "Well1_Seq0000" = "B16", "Well3_Seq0002" = "B16",
    "Well2_Seq0001" = "3T3", "Well4_Seq0003" = "3T3",
    "Well5_Seq0007" = "PF", "Well7_Seq0005" = "PF"
  )),
  "N4-2-13" = hash(c(
    "Well1_Seq0000" = "B16", "Well5_Seq0007" = "B16",
    "Well2_Seq0001" = "3T3", "Well6_Seq0006" = "3T3",
    "Well3_Seq0002" = "PF", "Well7_Seq0005" = "PF"
  ))
))

image_sample_map <- hash(c(
  "N4-2-7" = hash(c(
    "Well1_Seq0000" = "A", "Well2_Seq0001" = "A", "Well5_Seq0007" = "A",
    "Well3_Seq0002" = "B", "Well4_Seq0003" = "B", "Well7_Seq0005" = "B"
  )),
  "N4-2-9" = hash(c(
    "Well1_Seq0000" = "A", "Well2_Seq0001" = "A", "Well5_Seq0007" = "A",
    "Well3_Seq0002" = "B", "Well4_Seq0003" = "B", "Well7_Seq0005" = "B"
  )),
  "N4-2-13" = hash(c(
    "Well1_Seq0000" = "TC", "Well2_Seq0001" = "TC", "Well3_Seq0002" = "TC",
    "Well5_Seq0007" = "COLI", "Well6_Seq0006" = "COLI", "Well7_Seq0005" = "COLI"
  ))
))

donor_levels <- c(
  "PF",
  "3T3",
  "B16"
)

sample_levels <- c(
  "A", "B", "TC", "COLI"
)

# assign donor and sample
df_overlap$donor <- "NONE"
df_overlap$sample <- "NA"
for (cur_exp in unique(df_overlap$exp)){
  for (cur_image in unique(df_overlap[(df_overlap$exp == cur_exp),]$image)){
    df_overlap[(df_overlap$exp == cur_exp) &
               (df_overlap$image == cur_image),]$donor <- image_donor_map[[cur_exp]][[cur_image]]
    df_overlap[(df_overlap$exp == cur_exp) &
               (df_overlap$image == cur_image),]$sample <- image_sample_map[[cur_exp]][[cur_image]]
  }
}
df_overlap$donor <- factor(df_overlap$donor, levels = donor_levels)
df_overlap$sample <- factor(df_overlap$sample, levels = sample_levels)

# # calculate mean eccentricity and plot as well
# aggr_eccentricity <- setNames(
#   aggregate(df_dc$AreaShape_Eccentricity,
#             list(df_dc$exp, df_dc$donor, df_dc$sample,
#                  df_dc$Metadata_Site, df_dc$Metadata_Time),
#             mean),
#   c("exp", "donor", "sample", "site", "time", "mean_eccentricity")
# )
# 
# # merge with overlap
# df_overlap <- merge(x = df_overlap, y = aggr_eccentricity,
#       by = c("exp", "donor", "sample", "site", "time"),
#       all.x = T)
# --- END
```

```{r fig_overlap_time, fig.height = 8, fig.width = 5}
# go through sites
ylim <- c(0, 1)
ylim_ecc <- c(0.4, 0.8)
lwd <- 2

par(mfrow = c(6, 3))
for (cur_exp in unique(df_overlap$exp)) {
  for (cur_sample in unique(df_overlap$sample)) {
    for (cur_donor in unique(df_overlap$donor)) {
      for (cur_site in unique(df_overlap$site)) {
        cur_df_overlap <- df_overlap[
            (df_overlap$exp == cur_exp)
            & (df_overlap$donor == cur_donor)
            & (df_overlap$sample == cur_sample)
            & (df_overlap$site == cur_site), ]
        
        # check if there is data
        if (nrow(cur_df_overlap) > 0) {
          # calculate lines of best fit
          lin_mod_overlap <- lm(ratio_dc_overlapping ~ time, data = cur_df_overlap)
          lin_mod_donor_area <- lm(ratio_donor_area ~ time, data = cur_df_overlap)
          # lin_mod_ecc <- lm(mean_eccentricity ~ time, data = cur_df_overlap)
          
          # plot
          plot(ratio_donor_area ~ time, data = cur_df_overlap, col = "Magenta",
               ylim = ylim, ylab = "ratio")
          abline(lin_mod_donor_area, col = "Magenta", lwd = lwd)
          par(new = T)
          plot(ratio_dc_overlapping ~ time, data = cur_df_overlap, col = "Cyan",
               main = paste(cur_exp, "-", cur_donor, cur_sample),
               ylim = ylim, ylab = "ratio")
          abline(lin_mod_overlap, col = "Cyan", lwd = lwd)
          # par(new = T)
          # plot(mean_eccentricity ~ time, data = cur_df_overlap, col = "Black",
          #      ylim = ylim_ecc, ylab = "ratio",
          #      axes = FALSE, bty = "n")
          # abline(lin_mod_ecc, col = "Black", lwd = lwd)
          # axis(side = 4, at = pretty(ylim_ecc))
          # mtext("z", side=4, line=3)
          # plot(mean_eccentricity ~ time, data = cur_df_overlap, col = "Black",
          #      ylim = ylim, ylab = "ratio")
        }
      }
    }
  }
}
```

---
TUE 23/10/2018
---
Do a scatter plot to see if overlapping DCs correlate with the donor area.
```{r fig_overlap_scatter, fig.height = 3, fig.width = 4}
library(scales)

par(mfrow = c(2,2))
alpha_val <- 0.2
lwd <- 2

for (cur_exp in unique(df_overlap$exp)) {
  cur_df_overlap <- df_overlap[
          (df_overlap$exp == cur_exp), ]
  
  # calculate lines of best fit
  lin_mod <- lm(ratio_dc_overlapping ~ ratio_donor_area,data = cur_df_overlap)
  
  xlim <- c(0, 1)
  ylim <- c(0, 1)
  plot(ratio_dc_overlapping ~ ratio_donor_area,
       data = cur_df_overlap[(cur_df_overlap$donor == "B16"),],
       col = alpha("Black", alpha_val), pch = 16, cex = 0.5,
       xlim = xlim, ylim = ylim)
  par(new = T)
  plot(ratio_dc_overlapping ~ ratio_donor_area,
       data = cur_df_overlap[(cur_df_overlap$donor == "3T3"),],
       col = alpha("Cyan", alpha_val), pch = 16, cex = 0.5,
       xlim = xlim, ylim = ylim)
  par(new = T)
  plot(ratio_dc_overlapping ~ ratio_donor_area,
       data = cur_df_overlap[(cur_df_overlap$donor == "PF"),],
       col = alpha("Magenta", alpha_val), pch = 16, cex = 0.5,
       xlim = xlim, ylim = ylim, main = cur_exp)
  abline(lin_mod, col = "Gray", lwd = lwd)
  
  # --- START SAT 03/11/2018
  # add eccentricity
  # calculate lines of best fit
  lin_mod <- lm(ratio_dc_donor ~ mean_eccentricity,data = cur_df_overlap)
  
  xlim <- c(0.4, 0.8)
  ylim <- c(0, 3)
  plot(ratio_dc_donor ~ mean_eccentricity,
       data = cur_df_overlap[(cur_df_overlap$donor == "B16"),],
       col = alpha("Black", alpha_val), pch = 16, cex = 0.5,
       xlim = xlim, ylim = ylim)
  par(new = T)
  plot(ratio_dc_donor ~ mean_eccentricity,
       data = cur_df_overlap[(cur_df_overlap$donor == "3T3"),],
       col = alpha("Cyan", alpha_val), pch = 16, cex = 0.5,
       xlim = xlim, ylim = ylim)
  par(new = T)
  plot(ratio_dc_donor ~ mean_eccentricity,
       data = cur_df_overlap[(cur_df_overlap$donor == "PF"),],
       col = alpha("Magenta", alpha_val), pch = 16, cex = 0.5,
       xlim = xlim, ylim = ylim, main = cur_exp)
  abline(lin_mod, col = "Gray", lwd = lwd)
  # --- END
}
```

Compare the values between samples
```{r fig_overlap, fig.height = 1.5, fig.width = 3}
require(ggplot2)

# group A and B to TC
if (any(df_overlap$sample %in% c("A", "B")) != F){
  df_overlap[df_overlap$sample %in% c("A", "B"),]$sample <- "TC"
}
df_overlap$donor <- factor(df_overlap$donor, levels = donor_levels)

ggplot(data = df_overlap, aes(x=factor(donor), y=ratio_dc_overlapping)) +
  geom_violin(trim=FALSE) + geom_boxplot(width=0.1) + facet_wrap(~sample, ncol = 2) +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text = element_blank()
        ) +
  xlab ("Donors") + ylab("Overlapping DC (ratio)") + ylim(0, 1)

ggplot(data = df_overlap, aes(x=factor(donor), y=ratio_donor_area)) +
  geom_violin(trim=FALSE) + geom_boxplot(width=0.1) + facet_wrap(~sample, ncol = 2) +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text = element_blank()
        ) +
  xlab ("Donors") + ylab("Donor area (ratio)") + ylim(0, 1)

ggplot(data = df_overlap, aes(x=factor(donor), y=ratio_dc_donor)) +
  geom_violin(trim=FALSE) + geom_boxplot(width=0.1) + facet_wrap(~sample, ncol = 2) +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text = element_blank()
        ) +
  xlab ("Donors") + ylab("Overlapping DC to donor area (ratio)") +
  geom_hline(yintercept = 1, linetype = "dashed", colour = "grey")
```

